{application,couchdb,
             [{description,"CouchDB Erlang/Elixir client"},
              {pkg_name,"couchdb"},
              {vsn,"2.1.0-beta"},
              {licenses,["MIT"]},
              {modules,[couchdb,couchdb_app,couchdb_attachments,
                        couchdb_changes,couchdb_databases,
                        couchdb_design_documents,couchdb_doc,
                        couchdb_documents,couchdb_ejson,couchdb_httpc,
                        couchdb_mango,couchdb_server,couchdb_sup,couchdb_util,
                        couchdb_uuids,couchdb_view,legacy_couchdb,
                        legacy_couchdb_attachments,
                        legacy_couchdb_changes_stream,
                        legacy_couchdb_changes_sup,legacy_couchdb_view_stream,
                        legacy_couchdb_view_sup,legacy_gen_changes]},
              {registered,[couchdb_sup]},
              {applications,[kernel,stdlib,asn1,crypto,public_key,ssl,idna,
                             jiffy,hackney]},
              {included_applications,[]},
              {env,[]},
              {mod,{couchdb_app,[]}},
              {links,[{"Github","https://github.com/eyedouble/couchdb"},
                      {"Travis CI",
                       "https://travis-ci.org/eyedouble/couchdb"}]},
              {files,["src","include","rebar.config","README.md","LICENSE"]}]}.
